import EventDetailClient from "./EventDetailClient";

// Change this to false. This tells Next.js that ONLY the pages
// generated by generateStaticParams exist at build time.
export const dynamicParams = false;

// Return a placeholder string parameter.
// Next.js will build an HTML shell for `/events/id`.
export function generateStaticParams() {
  return [{ eventId: "id" }];
}

export default function EventDetailPage() {
  return <EventDetailClient />;
}
