export const PREDEFINED_ROLES = [
  'Advisor',
  'Advisor - Early Discount',
  'Advisor - Early Discount - No Show',
  'Advisor - No Show',
  'Advisor - Late Registration',
  'Advisor - Late Registration - No Show',
  'Ceremony Team',
  'Ceremony Team - Early Discount',
  'Ceremony Team - Early Discount - No Show',
  'Ceremony Team - No Show',
  'Ceremony Team - Late Registration',
  'Ceremony Team - Late Registration - No Show',
  'Cook Crew',
  'Cook Crew - Early Discount',
  'Cook Crew - Early Discount - No Show',
  'Cook Crew - No Show',
  'Cook Crew - Late Registration',
  'Cook Crew - Late Registration - No Show',
  'Day Participant',
  'Day Participant - Early Discount',
  'Day Participant - Early Discount - No Show',
  'Day Participant - No Show',
  'Day Participant - Late Registration',
  'Day Participant - Late Registration - No Show',
  'Elangomat',
  'Elangomat - Early Discount',
  'Elangomat - Early Discount - No Show',
  'Elangomat - No Show',
  'Elangomat - Late Registration',
  'Elangomat - Late Registration - No Show',
  'Feast Only',
  'Feast Only - Early Discount',
  'Feast Only - Early Discount - No Show',
  'Feast Only - No Show',
  'Feast Only - Late Registration',
  'Feast Only - Late Registration - No Show',
  'Health & Safety',
  'Health & Safety - Early Discount',
  'Health & Safety - Early Discount - No Show',
  'Health & Safety - Late Registration - No Show',
  'Ordeal Candidate',
  'Ordeal Candidate - Early Discount',
  'Ordeal Candidate - Early Discount - No Show',
  'Ordeal Candidate - No Show',
  'Ordeal Candidate - Late Registration',
  'Ordeal Candidate - Late Registration - No Show',
  'Ordeal Master',
  'Ordeal Master - Early Discount',
  'Ordeal Master - Early Discount - No Show',
  'Ordeal Master - No Show',
  'Ordeal Master - Late Registration',
  'Ordeal Master - Late Registration - No Show',
  'Participant',
  'Participant - Early Discount',
  'Participant - Early Discount - No Show',
  'Participant - No Show',
  'Participant - Late Registration',
  'Participant - Late Registration - No Show',
  'Staff Adviser',
  'Staff Adviser - Early Discount',
  'Staff Adviser - Early Discount - No Show',
  'Staff Adviser - No Show',
  'Staff Adviser - Late Registration',
  'Staff Adviser - Late Registration - No Show',
  'Amangamek-Wipit Lodge Member',
  'Amangamek-Wipit Lodge Member Day Attendee',
  'OA Member Feast Only',
  'OA Ordeal Candidate'
];

export const PAYMENT_METHODS = [
  'online',
  'council',
  'transfer',
  'on-site'
];
